name: main
description: main package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: "3.24.5"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.3
  http: ^1.2.1
  injectable: ^2.5.0
  logger: 2.3.0
  get_it: ^8.0.3
  go_router: ^14.2.13
  url_strategy: ^0.2.0

  core:
    path: ../../packages/core

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  build_runner:
  coverage:
  injectable_generator: